name: Deploy Production on Vercel

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  common-affected-tasks:
    name: Detect apps that are modified
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Generate Prime Numbers
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: echo 'Cache Hit'
        
      - name: Install dependecies
        run: yarn install --prefer-offline --frozen-lockfile # will run `yarn install` command
